version: "3"
networks:
  global-network:
services:
  postgres:
    image: "postgres:latest"
    restart: always
    environment:
      - POSTGRES_PASSWORD=123123nik
      - DB_USER=postgres
      - DB_HOST=postgres
      - DB_NAME=postgres
      - DB_PASSWORD=123123nik
      - DB_PORT=5432
    volumes:
      - ./dataPostgres:/app/src/dataPostgres
    networks:
      - global-network
  nginx:
    depends_on:
      - api
      - client
    restart: always
    build:
      dockerfile: Dockerfile
      context: ./nginx
    ports:
      - "3000:80"
    networks:
      - global-network
  api:
    build:
      dockerfile: Dockerfile
      context: "./server"
    ports:
      - "5000:5000"
    volumes:
      - /app/node_modules
      - ./server:/app
    networks:
      - global-network
  client:
    stdin_open: true
    environment:
      - CHOKIDAR_USEPOLLING=true
    build:
      dockerfile: Dockerfile
      context: ./client
    volumes:
      - /app/node_modules
      - ./client:/app
    networks:
      - global-network