const Router = require('express')
const router = new Router()
const userRouter = require('./userRouter')
const taskRouter = require('./taskRouter')
const decisionRouter = require('./decisionRouter')
const colourRouter = require('./colourRouter')
const feedbackRouter = require('./feedbackRouter')
const taskroleRouter = require('./taskroleRouter')
const taskstatusRouter = require('./taskstatusRouter')
const userroleRouter = require('./userroleRouter')
const usercreatetaskRouter = require('./usercreatetaskRouter')
const usertaketaskRouter = require('./usertaketaskRouter')
router.use('/user',userRouter)
router.use('/task',taskRouter)
router.use('/decision',decisionRouter)
router.use('/colour',colourRouter)
router.use('/feedback',feedbackRouter)
router.use('/taskrole',taskroleRouter)
router.use('/taskstatus',taskstatusRouter)
router.use('/userrole',userroleRouter)
router.use('/usercreatetask',usercreatetaskRouter)
router.use('/usertaketask',usertaketaskRouter)
module.exports = router
