const Router = require('express')
const router = new Router()
const taskController = require('../controllers/taskController')
const checkRole = require('../middleware/checkRoleMiddleware')
router.post('/add', taskController.create)
router.get('/taskcheckers', taskController.taskcheckers)
router.get('/AllTask', taskController.AllTask)
router.get('/getAll', taskController.getAll)
router.patch('/complete', taskController.complete)
router.get('/history', taskController.history)
router.get('/:TaskId', taskController.getOne)
router.patch('/updateTask',taskController.updateTask)
router.patch('/updateTaskAndDecision',taskController.updateTaskAndDecision)
router.patch('/addDecision',taskController.addDecision)
router.get('/:TaskId', taskController.getOne)
router.delete('/',taskController.delete)
module.exports = router